version: "3.8"

services:
  checkmk:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk
    hostname: checkmk
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - checkmk_data:/omd/sites
    environment:
      - CMK_SITE_ID=monitoring
      - CMK_PASSWORD=cmkadmin
      - TZ=America/Sao_Paulo

volumes:
  checkmk_data:
